### ISSUE TITLE
Does not build with latest SBCL - type error

### ISSUE THREAD

**Issue by quicklisp** [g000001/tagger#7]
I get this: 

    ; caught WARNING:
    ;   Cannot coerce SINGLE-FLOAT to FIXNUM

Full log is here: http://report.quicklisp.org/2019-02-21/failure-report/tagger.html#tagger

**Comment by g000001** [comment]
fixed in https://github.com/g000001/tagger/commit/ed37a55de3d2c13a781fae60f881284b4101e2a6
thank you!
